image: golang:1.17

variables:
  TZ: Asia/Tokyo

stages:
  - test

test-project:
  stage: test
  script:
    - go test ./... -cover -coverprofile=cover.out -covermode=atomic -v
    - go tool cover -func=cover.out
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d?%)\s*$/'
